# Homebrew extensions
# Bundler for non-Ruby dependencies from Homebrew, Homebrew Cask,
# Mac App Store, Whalebrew and Visual Studio Code.
tap "homebrew/bundle"

# =============================================================================
# System Utilities
# =============================================================================
brew "coreutils" # required for go development
brew "ctop" # https://ctop.sh/
brew "ncdu" # https://dev.yorhel.nl/ncdu
brew "tmux"
brew "bat"
brew "eza" # https://github.com/eza-community/eza - A modern replacement for ls
brew "htop"
brew "grep"
brew "tldr" # https://tldr.sh/
brew "awscli"
brew "git"
brew "git-delta" # https://github.com/dandavison/delta
brew "mas" # https://github.com/mas-cli/mas
brew "kubernetes-cli"
brew "kustomize"
brew "libpq"
brew "jq"
brew "fzf"
brew "zoxide" # https://github.com/ajeetdsouza/zoxide
brew "kind"

# Version Manager
brew "asdf"

# =============================================================================
# Zsh
# =============================================================================
brew "zsh"

# Zsh Plugin Manager
brew "antigen"                 # https://github.com/zsh-users/antigen replaces zplug
brew "zsh-autosuggestions"     # https://github.com/zsh-users/zsh-autosuggestions
brew "zsh-syntax-highlighting" # https://github.com/zsh-users/zsh-syntax-highlighting

brew "powerlevel10k" # https://github.com/romkatv/powerlevel10k

# =============================================================================
# Editors
# =============================================================================
cask "visual-studio-code"

# =============================================================================
# Desktop Apps via Homebrew
# =============================================================================
cask "spotify"

# Browser
cask "firefox"

# knowledge Management
cask "obsidian"

# Communication
cask "whatsapp"

# VPN Client
cask "viscosity"

# Wallet desktop application to maintain multiple cryptocurrencies
cask "ledger-live"

# Bruno a replacement for Postman and Insomnia
# In the documentation "Bruno" is listed as "bruno" is listed as Formula
# and not as Cask
# https://github.com/usebruno/bruno/issues/2948#issuecomment-2315564106
cask "bruno"


# =============================================================================
# Fonts
# =============================================================================
cask "font-jetbrains-mono"
cask "font-meslo-lg-nerd-font"

# =============================================================================
# Desktop Apps via App Store
# =============================================================================
mas "Things 3", id: 904280696
mas "Xcode", id: 497799835

# =============================================================================
# VSCode Extensions
# =============================================================================
vscode "GitHub.copilot"
vscode "VisualStudioExptTeam.vscodeintellicode"
vscode "dracula-theme.theme-dracula"
vscode "foxundermoon.shell-format"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "redhat.vscode-commons"
vscode "redhat.vscode-yaml"
vscode "wix.vscode-import-cost"
vscode "yoavbls.pretty-ts-errors"
vscode "ms-vscode.makefile-tools" # Makefile Tools
vscode "wix.vscode-import-cost"

# =============================================================================
# Eletrocnic Applications
# =============================================================================
cask "thonny" # Python IDE for beginners
cask "kicad" # Electronic Design Automation (EDA) software

# ==============================================================================
# Labs
# The following are tools that I am trying out and may not be part of my daily
# ==============================================================================

# https://headlamp.dev/
# Headlamp is a Kubernetes debugging tool that provides a visual interface
# for debugging your applications.
# It's a replacement for OpenLens - https://github.com/MuhammedKalkan/OpenLens
cask "headlamp"

# https://sw.kovidgoyal.net/kitty/
# A fast, featureful, GPU based terminal emulator replacement for iterm
brew "lazydocker"

brew "lazygit"

brew "zellij"

# Editor
cask "zed"

# Command line
cask "ghostty"

brew "neovim"

cask "arduino-ide"

# Jujutsu—a version control system
# https://github.com/jj-vcs/jj
brew "jj"
