# Homebrew extensions
tap "homebrew/bundle"

# tap "olets/tap" # zsh-abbr

# Terminal Utilities
brew "coreutils" # required for go development
brew "ctop" # https://ctop.sh/
brew "ncdu" # https://dev.yorhel.nl/ncdu
brew "tmux"
brew "bat"
brew "eza" # https://github.com/eza-community/eza - A modern replacement for ls
brew "htop"
brew "grep"
brew "tldr" # https://tldr.sh/
brew "awscli"
brew "git"
brew "git-delta" # https://github.com/dandavison/delta
brew "mas" # https://github.com/mas-cli/mas
brew "kubernetes-cli"
brew "kustomize"
brew "libpq"
brew "jq"
brew "fzf"
brew "zoxide" # https://github.com/ajeetdsouza/zoxide
cask "ledger-live"
brew "kind"

# Version Manager
brew "asdf"

# Terminal
cask "iterm2" # https://iterm2.com/
cask "kitty"

brew "zsh"
brew "zplug"  # https://github.com/zplug/zplug
brew "zsh-autosuggestions"     # https://github.com/zsh-users/zsh-autosuggestions
brew "zsh-syntax-highlighting" # https://github.com/zsh-users/zsh-syntax-highlighting

# Editors
brew "neovim"
cask "visual-studio-code"
cask "zed"

# Music Apps
cask "spotify"

# Browser
cask "firefox"

# knowledge Management
cask "obsidian"

# Communication
cask "whatsapp"

# VPN Client
cask "viscosity"

# Fonts
cask "font-jetbrains-mono"
cask "font-meslo-lg-nerd-font"

# App Store
mas "Things 3", id: 904280696
mas "Xcode", id: 497799835

# VSCode extensions
vscode "GitHub.copilot"
vscode "VisualStudioExptTeam.vscodeintellicode"
vscode "dracula-theme.theme-dracula"
vscode "foxundermoon.shell-format"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "redhat.vscode-commons"
vscode "redhat.vscode-yaml"
vscode "wix.vscode-import-cost"
vscode "yoavbls.pretty-ts-errors"
vscode "ms-vscode.makefile-tools" # Makefile Tools
vscode "wix.vscode-import-cost"

# ==============================================================================
# Labs
# The following are tools that I am trying out and may not be part of my daily
# ==============================================================================

# https://headlamp.dev/
# Headlamp is a Kubernetes debugging tool that provides a visual interface
# for debugging your applications.
# It's a replacement for OpenLens - https://github.com/MuhammedKalkan/OpenLens
cask "headlamp"

# https://sw.kovidgoyal.net/kitty/
# A fast, featureful, GPU based terminal emulator replacement for iterm
cask "kitty"
