# =======================================================
# homebrew
# =======================================================
export PATH=""${HOMEBREW_PREFIX}"/sbin:$PATH"

# Support Intel/ARM Homebrew
if [ "$(arch)" = "arm64" ]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
else
    eval "$(/usr/local/bin/brew shellenv)"
fi

# =======================================================
# zsh
# =======================================================
export ZSH_COMPDUMP=$ZH/cache/.zcompdump-${HOST}-${ZSH_VERSION}

# antigen
source "${HOMEBREW_PREFIX}/share/antigen/antigen.zsh"

# install antigen plugins
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-completions

# load the theme
antigen apply

# zsh-autosuggestions
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=8"

# =======================================================
# zoxide
# =======================================================
# zoxide
# Setup zoxide on your shell, the "cd replacement"
eval "$(zoxide init zsh)"

# =======================================================
# bat
# =======================================================

export BAT_STYLE="changes,header"
export BAT_THEME="Dracula" # GitHub

# =======================================================
# asdf
# =======================================================

# load asdf
source "${HOMEBREW_PREFIX}"/opt/asdf/libexec/asdf.sh

# set asdf plugins home
source ~/.asdf/plugins/java/set-java-home.zsh
source ~/.asdf/plugins/golang/set-env.zsh

# =======================================================
# neovim
# =======================================================

# Editor Neovim
export EDITOR="nvim"

# Alias
source ~/.zsh_aliases
source ~/.zsh_env

export PATH="/opt/homebrew/opt/libpq/bin:$PATH"
export PATH="/opt/homebrew/opt/mysql-client/bin:$PATH"

exec $ZSH_PATH
